---
# tasks file for base-os
#- include: opensuse.yml
#  when: ansible_distribution == 'openSUSE Leap'
#  tags: package
- include: sles15.yml
  when: ansible_distribution == 'SLES'
  tags: package

- include: leap15.yml
  when: ansible_distribution == 'openSUSE Leap'
  tags: package

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: package
